### ISSUE TITLE
Open to implement for milestone v1.0

### ISSUE THREAD

**Issue by maschmann** [maschmann/php-ansible#1]
To implement before v1.0

* [x] ansible-galaxy integration for automated install/upgrade of needed plugins (optional)
* [x] Override for timeout default in factory
* [x] ~~Refactor e.g. sudo() to have optional parameters (true). Makes imeplementation in php-deploy easier~~
* [x] Implement parameter analyzer for --extra-vars to be able to input either string or array of options
* [x] centralize parameter string/array checks
* [x] ~~abstract shell_exec() for proper UnitTesting~~
* [x] use proper english in README
* [x] add sf versions 2.6/2.7 to travis tests
* [x] flexible/configurable timeout for process component
